In [1]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np
arr = np.array([0,1,2,3,4,5])
print("Datatpe of arr: ",arr.dtype)

Datatpe of arr:  int64


In [ ]:
# 2. Given a NumPy array 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)

float64


In [ ]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([1+2j, 3-4j, 5+6j])
print(arr.dtype)

complex128


In [ ]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

arr = arr.astype(np.float32)
print(arr.dtype)

float32


In [ ]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1.5, 2.6, 3.7])
arr = arr.astype(np.float32)
print(arr.dtype)

float32


In [ ]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype.

def array_attributes(arr1):
  shape = arr1.shape
  size = arr1.size
  data_type = arr1.dtype
  return shape, size, data_type

arr1 = array_attributes(np.array([[1,2,3],[4,5,6]]))
print("Shape:", arr1[0])
print("Size:", arr1[1])
print("Data Type:", arr1[2])

Shape: (2, 3)
Size: 6
Data Type: int64


In [ ]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

def array_dimension(arr2):
  return arr2.ndim

arr2 = array_dimension(np.array([[4,4,3],[7,5,1]]))
print("Dimensionality:", arr2)

Dimensionality: 2


In [ ]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

def item_size_info(arr3):
  item_size_bytes = arr3.itemsize
  total_size_bytes = arr3.nbytes
  return item_size_bytes, total_size_bytes

arr3 = item_size_info(np.array([[4,4,3],[7,5,1]]))
print("Item Size (bytes):", arr3[0])
print("Total Size (bytes):", arr3[1])

Item Size (bytes): 8
Total Size (bytes): 48


In [ ]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(arr4):
  return arr4.strides

arr4 = array_strides(np.array([[4,4,3],[7,5,1]]))
print("Strides:", arr4)

Strides: (24, 8)


In [ ]:
arr = np.array([[4,4,3],[7,5,1]])
arr

array([[4, 4, 3],
       [7, 5, 1]])

In [ ]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

def shape_stride_relationship(arr4):
  shape = arr4.shape
  stride = arr4.strides
  return shape, stride

shape, stride = shape_stride_relationship(np.array([[4,4,3],[7,5,1]]))
print("Shape:", shape)
print("Strides:", stride)

Shape: (2, 3)
Strides: (24, 8)


In [ ]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

def create_zeros_array(n):
  arr = np.zeros(n)
  return arr

n = int(input("Enter any number: "))
arr = create_zeros_array(n)
print(arr)

Enter any number: 5
[0. 0. 0. 0. 0.]


In [ ]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(row,col):
  arr = np.ones((row,col))
  return arr

row = int(input("Enter row number: "))
col = int(input("Enter column number: "))
arr = create_ones_matrix(row,col)
print(arr)

Enter row number: 3
Enter column number: 4
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

def generate_range_array(start,stop,step):

  return np.arange(start,stop,step)

start = 1
stop = 10
step = 2
array = generate_range_array(start,stop,step)
print("Range array: ",array)

Range array:  [1 3 5 7 9]


In [ ]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

def generate_linear_space(start,stop,num):

  return np.linspace(start,stop,num)

start = 1.0
stop = 2.0
num = 5
array = generate_linear_space(start,stop,num)
print("Linear space array: ",array)

Linear space array:  [1.   1.25 1.5  1.75 2.  ]


In [ ]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
  arr = np.eye(n)
  return arr

n = int(input("Enter any number: "))
arr = create_identity_matrix(n)
print(arr)

Enter any number: 5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.

def lst_to_array(lst):
  arr = np.array(lst)
  return arr

lst = [2,3,4,5,6]
arr = lst_to_array(lst)
print("Numpy array: ",arr)

Numpy array:  [2 3 4 5 6]


In [ ]:
org_array = np.array([[1,2,3],[4,5,6]])
view_array = org_array.view()
org_array[0,0] = 10

print("Original array: \n",org_array)
print("View array: \n",view_array)

Original array: 
 [[10  2  3]
 [ 4  5  6]]
View array: 
 [[10  2  3]
 [ 4  5  6]]


In [ ]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,8],[7,8,9]])

res = np.concatenate((arr1,arr2), axis = 1)
print(res)

[[1 2 3 1 2 8]
 [4 5 6 7 8 9]]


In [ ]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[7, 8],[9, 10]])
res = np.concatenate((arr1,arr2),axis = 1)

print(res)

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [ ]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

def stacks_array(arr):

  return np.vstack(arr)

arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[7, 8, 9],[10, 11, 12]])
arr3 = np.array([[13, 14, 15],[16, 17, 18]])

res = stacks_array([arr1,arr2,arr3])
print("Vertically stacked array: \n",res)

Vertically stacked array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.


def create_integer_array(start, stop, step=1):

    return np.arange(start, stop + 1, step)


start = 1
stop = 10
step = 2
integer_array = create_integer_array(start, stop, step)
print("Integer Array:", integer_array)


Integer Array: [1 3 5 7 9]


In [ ]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

def spaced_values():

  return np.linspace(0,1,10)

print("Spaced equally values: ", spaced_values())

Spaced equally values:  [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

def logarithmatically_values():

  return np.logspace(0,3,5)

print("Logarithmatically values: ", logarithmatically_values())

Logarithmatically values:  [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100

import pandas as pd

data = np.random.randint(1,101, size = (5,3))
df = pd.DataFrame(data, columns = ['column1','column2','column2'])
print("Pandas dataframe: \n",df)

Pandas dataframe: 
    column1  column2  column2
0       21       53       84
1       28       83       35
2       14       78       95
3       49       47       94
4       43       60       22


In [ ]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

def rep_neg(df,col_name):

  df[col_name] = np.where(df[col_name] < 0, 0, df[col_name])
  return df

data = {'A': [1, 2, -3, 4, -5],
        'B': [5, -6, 7, -8, 9]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df_updated = rep_neg(df, 'A')

print("\nDataFrame after replacing negative values with zeros:")
print(df_updated)

Original DataFrame:
   A  B
0  1  5
1  2 -6
2 -3  7
3  4 -8
4 -5  9

DataFrame after replacing negative values with zeros:
   A  B
0  1  5
1  2 -6
2  0  7
3  4 -8
4  0  9


In [ ]:
# 26. Access the 3rd element from the given NumPy array

arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

In [ ]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

arr_2d[1,2]

6

In [ ]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr = np.array([3, 8, 2, 10, 5, 7])


arr[arr > 5]

array([ 8, 10,  7])

In [ ]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:5]

array([3, 4, 5])

In [ ]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.



In [ ]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def filt_elem(arr,threshold):

  return arr[arr > threshold]

arr = np.array([7,5,3,1,8,9,12,65])
threshold = 10

print("Elements greater than a threshold: \n", filt_elem(arr,threshold))

Elements greater than a threshold: 
 [12 65]


In [ ]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

def extract_elem(arr_3d, indices_dim1, indices_dim2, indices_dim3):

    return arr_3d[indices_dim1, indices_dim2, indices_dim3]

arr_3d = np.arange(24).reshape(2, 3, 4)
indices_dim1 = np.array([0, 1])
indices_dim2 = np.array([1, 2])
indices_dim3 = np.array([2, 3])

print("Extracted elements: \n", extract_elem(arr_3d, indices_dim1, indices_dim2, indices_dim3))

Extracted elements: 
 [ 6 23]


In [ ]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

def fil_elem_cond(arr, cond_1, cond_2):

  return arr[np.logical_and(cond_1,cond_2)]


arr = np.array([1, 5, 3, 8, 2, 10])
cond_1 = arr > 3
cond_2 = arr % 2 == 0
print("Filtered Elements with Both Conditions Satisfied:", fil_elem_cond(arr, cond_1, cond_2))

Filtered Elements with Both Conditions Satisfied: [ 8 10]


In [ ]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

def extract_elem(arr,row_indices,col_indices):

  return arr[row_indices,col_indices]

arr = np.array([[2,4,9],
                  [8,1,3],
                  [7,3,5]])
row_indices = np.array([0,1,2])
col_indices = np.array([1,2,1])
print("Extracted elements: \n", extract_elem(arr,row_indices,col_indices))

Extracted elements: 
 [4 3 3]


In [ ]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.array([[2,4,9],
                  [8,1,3],
                  [7,3,5]])

result = arr + 5
print("Result after adding 5 to each element: \n",result)

Result after adding 5 to each element: 
 [[ 7  9 14]
 [13  6  8]
 [12  8 10]]


In [ ]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

result = arr1.T * arr2

print("Result after multiplying each row of arr2 by the corresponding element in arr1:")
print(result)


Result after multiplying each row of arr2 by the corresponding element in arr1:
[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [ ]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])
result = arr1.T + arr2

print("Result after adding arr1 to each row of arr2:")
print(result)

Result after adding arr1 to each row of arr2:
[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [ ]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1 = np.array([[1],
                  [2],
                  [3]])
arr2 = np.array([[4, 5, 6]])

result = arr1 + arr2

print("Result after adding:")
print(result)

Result after adding:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

arr1 = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr2 = np.array([[1, 2],
                  [3, 4]])

result = arr1 * np.reshape(arr2,(2,2,1))
print("Result after multiplication:")
print(result)


Result after multiplication:
[[[ 1  2  3]
  [ 8 10 12]]

 [[ 3  6  9]
  [16 20 24]]]


In [ ]:
# 41. Calculate column wise mean for the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr, axis  =1))

[2. 5.]


In [ ]:
# 42. Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr,axis = 1))

[3 6]


In [ ]:
# 43. For the given array, find indices of maximum value in each column

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.argmax(arr, axis = 1))

[2 2]


In [ ]:
# 44. For the given array, apply custom function to calculate moving sum along rows.

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.cumsum(arr, axis = 1))

[[ 1  3  6]
 [ 4  9 15]]


In [ ]:
# 45. In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])

all_even = np.all(arr % 2 == 0, axis=0)

print("Are all elements in each column even?", all_even)

Are all elements in each column even? [False False False]


In [ ]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

original_array = np.array([1, 2, 3, 4, 5, 6])

m, n = 2,3
arr = np.reshape(original_array,(m,n))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 47. Create a function that takes a matrix as input and returns the flattened array.

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flatten_arr(input_matrix):

  return input_matrix.flatten()

print(flatten_arr(input_matrix))

[1 2 3 4 5 6]


In [ ]:
# 48. Write a function that concatenates two given arrays along a specified axis.

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

def concat_arr(array1, array2, axis):

  return np.concatenate((array1, array2), axis = axis)

print(concat_arr(array1, array2, axis = 1),"\n")
print(concat_arr(array1, array2, axis = 0))

[[1 2 5 6]
 [3 4 7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_arr(original_array, num_split, axis):

  return np.split(original_array, num_split, axis= axis)

num_split = 3
splt_arr = split_arr(original_array, num_split, axis=0)
print(splt_arr[0])
print(splt_arr[1])
print(splt_arr[2])

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [ ]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

def arr_elem(original_array, indices_to_insert, values_to_insert, indices_to_delete):

  modified_arr = np.insert(original_array, indices_to_insert, values_to_insert)
  modified_arr = np.delete(original_array, indices_to_delete)
  return modified_arr

print(arr_elem(original_array, indices_to_insert, values_to_insert, indices_to_delete))

[1 3 5]


In [ ]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

arr1 = np.random.randint(1,100, size = (1,10))
arr2 = np.arange(1,11)

result = arr1 + arr2
print(result)

[[  3  45  47  59  32  53  75  59  55 103]]


In [ ]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

arr1 = np.arange(10,1, -1)
arr2 = np.arange(1,10)

result = arr2 - arr1

print(result)

[-9 -7 -5 -3 -1  1  3  5  7]


In [ ]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

arr1 = np.random.randint(1,50, size = (1,5))
arr2 = np.arange(1,6)

result = arr1 * arr2

print(result)

[[ 32  30 123   8 195]]


In [ ]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

arr1 = np.arange(2,11,2)
arr2 = np.arange(1,6)

result = arr1/arr2

print(result)

[2. 2. 2. 2. 2.]


In [ ]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

arr1 = np.arange(1,6)
arr2 = np.flip(arr1)

result = arr1 ** arr2

print(result)

[ 1 16 27 16  5]


In [ ]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def occurence(arr, sub_string):

  count = 0
  for string in arr:
    count+= string.count(sub_string)
  return count

sub_string =  'hello'
print(f"Number of occurrences of '{sub_string}':", occurence(arr,sub_string ))

Number of occurrences of 'hello': 3


In [ ]:
  # 57. Write a function that extracts uppercase characters from a NumPy array of strings.

  arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

  def extract_upper(arr):

    upper_char = ''
    for string in arr:
      for char in string:
        if char.isupper():
          upper_char+= char
    return upper_char

print(extract_upper(arr))

HWOAIGPT


In [ ]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def replace_string(arr, old_sub, new_sub):

  rep = np.char.replace(arr,old_sub,new_sub)
  return rep

old_sub = 'banana'
new_sub = 'mango'
print(replace_string(arr,old_sub,new_sub  ))

['apple' 'mango' 'grape' 'pineapple']


In [ ]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concat_string(arr1,arr2):

  concat = np.char.add(arr1,arr2)
  return concat

print(concat_string(arr1,arr2))

['HelloOpen' 'WorldAI']


In [3]:
# 60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def longest_string_length(arr):

  max_length = np.max(np.vectorize(len)(arr))
  return max_length

print("Length of the longest string: ", longest_string_length(arr))

Length of the longest string:  9


In [4]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

dataset = np.random.randint(1,1000, size = 100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard deviation:", std_deviation)

Dataset: [474 850 219 787 238 745 725 386  82 939 832 837 497 251 987 590 973 600
 568 885 605 557 811 492 644 798 948 823 932 745 870  55 571 299 276  77
 909 813 891 626 770 132 693 322 648 609 945 650 331 849   2 666 792 790
 864 594 528 687 936 176  45 475   8 986 274  39  72 878 283 674 833 373
 488 927 544 539 175 213  39 193 536 955 147 715 782 737 298 265 452 201
 415 180 943 889 942  42 101 532 327 585]
Mean: 552.93
Median: 592.0
Variance: 88194.3851
Standard deviation: 296.97539477202486


In [9]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

dataset = np.random.randint(1,100, size = 50)

percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

print("Dataset:", dataset)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Dataset: [65 95 12  2 64 33 53 73 64  8 79 39 67 73 61 86 18 63 18 69 91 25 39 41
 78 49 31 61 54 16 27 58 71 65 31  3  8 76 75 81 91 74 86 21 63 70 51 75
 93  1]
25th Percentile: 31.0
75th Percentile: 73.75


In [12]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([2, 3, 4, 5, 6])

corr_coef = np.corrcoef(set1, set2)[0,1]

print("Array 1:", set1)
print("Array 2:", set2)
print("Correlation Coefficient:", corr_coef)

Array 1: [1 2 3 4 5]
Array 2: [2 3 4 5 6]
Correlation Coefficient: 0.9999999999999999


In [13]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of matrix multiplication:")
print(result)


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of matrix multiplication:
[[ 58  64]
 [139 154]]


In [14]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

random_integers = np.random.randint(10, 1001, size=50)

percentiles = np.percentile(random_integers, [10, 50, 90])
first_quartile = np.percentile(random_integers, 25)
third_quartile = np.percentile(random_integers, 75)

print("Random integers:", random_integers)
print("\n10th Percentile:", percentiles[0])
print("Median (50th Percentile):", percentiles[1])
print("90th Percentile:", percentiles[2])
print("First Quartile:", first_quartile)
print("Third Quartile:", third_quartile)


Random integers: [332 567 757 699 768 125 212 215 132  75 277 835 790 145 191 241 218 832
 635 389 583 320 161 272 153  63 572  81 489 160 655 245  70 659 853 845
 681 529 847 387 840 219 814 461 555 377 288 577 126  96]

10th Percentile: 122.10000000000001
Median (50th Percentile): 382.0
90th Percentile: 832.3
First Quartile: 196.25
Third Quartile: 658.0


In [16]:
# 66. Create a NumPy array of integers and find the index of a specific element.

array = np.array([10, 20, 30, 40, 50])

element = 30
index = np.where(array == element)[0]

print("Array:", array)
print("Index of", element, ":", index)


Array: [10 20 30 40 50]
Index of 30 : [2]


In [20]:
# 67. Generate a random NumPy array and sort it in ascending order.

random_array = np.random.rand(10)

sorted_array = np.sort(random_array)

print("Random Array:", random_array)
print("Sorted Array:", sorted_array)


Random Array: [0.36825868 0.13780251 0.56421875 0.1024306  0.95006709 0.08909683
 0.7219138  0.61858299 0.29520079 0.49147466]
Sorted Array: [0.08909683 0.1024306  0.13780251 0.29520079 0.36825868 0.49147466
 0.56421875 0.61858299 0.7219138  0.95006709]


In [21]:
# 68. Filter elements >20  in the given NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr[arr > 20]

print("Original Array:", arr)
print("Filtered Array:", filtered_arr)


Original Array: [12 25  6 42  8 30]
Filtered Array: [25 42 30]


In [23]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.

arr = np.array([1, 5, 8, 12, 15])

filtered_arr = arr[arr % 3 == 0]

print("Original Array:", arr)
print("Filtered Array:", filtered_arr)

Original Array: [ 1  5  8 12 15]
Filtered Array: [12 15]


In [28]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

arr = np.array([10, 20, 30, 40, 50])

filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print("Original Array:", arr)
print("Filtered Array:", filtered_arr)

Original Array: [10 20 30 40 50]
Filtered Array: [20 30 40]


In [29]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

print("Byte Order:", byte_order)

Byte Order: =


In [30]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.

arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap(True)

print("After byte swapping:", arr)

After byte swapping: [16777216 33554432 50331648]


In [31]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder()

print("Original Array:", arr)
print("Swapped Array:", swapped_arr)

Original Array: [1 2 3]
Swapped Array: [16777216 33554432 50331648]


In [34]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder()

print("Original Array:", arr)
print("Swapped Array (conditionally):", swapped_arr)

Original Array: [1 2 3]
Swapped Array (conditionally): [16777216 33554432 50331648]


In [37]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

arr = np.array([1, 2, 3], dtype=np.int32)

array_byte_order = arr.dtype.byteorder
system_byte_order = sys.byteorder

byte_swapping_needed = array_byte_order != system_byte_order

print("Array Byte Order:", array_byte_order)
print("System Byte Order:", system_byte_order)
print("Byte Swapping Needed:", byte_swapping_needed)

Array Byte Order: =
System Byte Order: little
Byte Swapping Needed: True


In [38]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100

print("Original arr1:", arr1)
print("Modified copy_arr:", copy_arr)

Original arr1: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy_arr: [100   2   3   4   5   6   7   8   9  10]


In [39]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

matrix = np.random.randint(0, 10, (3, 3))

view_slice = matrix[:2, :2]

print("Original Matrix:", matrix)
print("\nSlice View:", view_slice)

view_slice[0, 0] = 100

print("\nModified Slice View:",view_slice)
print("\nOriginal Matrix After Modification:",matrix)

Original Matrix: [[7 0 8]
 [1 5 0]
 [1 2 7]]

Slice View: [[7 0]
 [1 5]]

Modified Slice View: [[100   0]
 [  1   5]]

Original Matrix After Modification: [[100   0   8]
 [  1   5   0]
 [  1   2   7]]


In [41]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[:2, :2]

view_b += 5

print("Original array_a:", array_a)

Original array_a: [[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

orig_array = np.arange(1, 9).reshape(2, 4)

reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 0] = 100

print("Original orig_array:", orig_array)

Original orig_array: [[100   2   3   4]
 [  5   6   7   8]]


In [46]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

data = np.random.randint(0, 10, (3, 4))

data_copy = data[data > 5].copy()

data_copy[0] = 100

print("Original data:")
print(data)

Original data:
[[5 5 7 0]
 [0 4 0 5]
 [2 0 6 1]]


In [47]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

add_result = A + B
sub_result = A - B

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nAddition Result:\n", add_result)
print("\nSubtraction Result:\n", sub_result)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition Result:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction Result:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [49]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

mult_result = np.dot(C, D)

print("Matrix C:\n", C)
print("\nMatrix D:\n", D)
print("\nMatrix Multiplication Result:\n", mult_result)

Matrix C:
 [[1 2]
 [3 4]
 [5 6]]

Matrix D:
 [[ 7  8  9 10]
 [11 12 13 14]]

Matrix Multiplication Result:
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [50]:
# 83. Create a matrix `E` and find its transpose.

E = np.array([[1, 2, 3],
              [4, 5, 6]])

E_transpose = np.transpose(E)

print("Matrix E:\n", E)
print("\nTranspose of Matrix E:\n", E_transpose)

Matrix E:
 [[1 2 3]
 [4 5 6]]

Transpose of Matrix E:
 [[1 4]
 [2 5]
 [3 6]]


In [51]:
# 84. Generate a square matrix `F` and compute its determinant.

F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

determinant_F = np.linalg.det(F)

print("Matrix F:\n", F)
print("\nDeterminant of Matrix F:", determinant_F)

Matrix F:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of Matrix F: 0.0


In [52]:
# 85. Create a square matrix `G` and find its inverse.

G = np.array([[1, 2],
              [3, 4]])

inverse_G = np.linalg.inv(G)

print("Matrix G:\n", G)
print("\nInverse of Matrix G:\n",inverse_G)

Matrix G:
 [[1 2]
 [3 4]]

Inverse of Matrix G:
 [[-2.   1. ]
 [ 1.5 -0.5]]
